### ISSUE TITLE
Quick start suggestion

### ISSUE THREAD

**Issue by Ratoncito** [cmatKhan/callingcards#4]
### Description of feature

So I Just finished running the quick start and it generated some folders and files but, there were some warnings and messages that seem like errors, so I am not sure if it actually worked or not. I would suggest putting in some screenshots or messages to let the user get a better idea of if the quick start successfully worked. 

Output full: 
<img width="839" alt="image" src="https://user-images.githubusercontent.com/56166993/185191750-48a0b2ee-1d95-463c-8a4d-1f65e3f23bb9.png">
<img width="899" alt="image" src="https://user-images.githubusercontent.com/56166993/185191856-42f5185e-4aea-44de-8e3c-4a31f518802e.png">

Tree of all the files outputted 
<img width="516" alt="image" src="https://user-images.githubusercontent.com/56166993/185192019-8c78e83b-9007-43f4-bdb1-1f5d0672f4de.png">
<img width="363" alt="image" src="https://user-images.githubusercontent.com/56166993/185192081-ed8cb5aa-780f-4fb2-a783-fcdaa5618102.png">
<img width="406" alt="image" src="https://user-images.githubusercontent.com/56166993/185192126-8788207c-c000-4d11-a063-705551a51df7.png">

**Comment by cmatKhan** [comment]
ok, so the code repo isn't really something a user needs to look at -- that is just the code to run the pipeline. If this does get added to nf-core, then you don't even have to pull the repo, you could just do:

nextflow run nf-core/callingcards <input>

Of course the repo does get downloaded, but it is all handled for the user by the software.

The only thing that the user needs to look at is the `results` directory. The `work` directory stores intermediate files. It is one of the pieces that allows for the `-resume` flag to work, also (`-resume` will pick up at the last completed step, if the pipeline execution is interrupted). But, after the pipeline completes, `work` can/should be deleted.

`results` should have a lot more in it though...there was an error w/the nextflow version. But it shouldn't be saying, "module not recognized" either. I labelled this a "bug" -- addressing that part now.

**Comment by Ratoncito** [comment]
I wouldn't worry about this immediately. This was an error that resulted from me running the quick start without the right version of nextflow installed. Maybe you could make a error that gets thrown if nextflow isnt the right version or something like that.

Best,

-Stu
_______________________________________________________________________________________


Stuart Fass

Bioinformatics Programmer for Dougherty Lab

Department of Genetics

Washington University in St. Louis, School of Medicine

Phone: +1.608.960.1753  l  Work: ***@***.***  l  Gmail: ***@***.***

________________________________

**Comment by cmatKhan** [comment]
ok -- instructions to update spack modules are here:

https://github.com/cmatKhan/callingcards/blob/main/docs/updating_modules_on_spack.md

I am not seeing that "module not found" error...concerned about that still.
