### ISSUE TITLE
No default_mammals 

### ISSUE THREAD

**Issue by Ratoncito** [cmatKhan/callingcards#9]
### Description of the bug

No default mammals thingy

### Command used and terminal output

```console
fasss@n001:/scratch/jdlab/stuart/calling_card_output$ nextflow run callingcards/main.nf     -profile default_mammals,singularity     -c callingcards/nextflow.config     --input ./sample_sheet_allen_data.csv     --fasta /ref/mblab/data/mouse     --output results_allen_data

N E X T F L O W  ~  version 22.04.5
Unknown configuration profile: 'default_mammals'
```

**Comment by cmatKhan** [comment]
That's a typo in the docs -- it should be `default_mammal`. fixing now

**Comment by Ratoncito** [comment]
[cid:ee1a1bc7-2f6f-495a-b077-c893419dad67]


Best,

-Stu
_______________________________________________________________________________________


Stuart Fass

Bioinformatics Programmer for Dougherty Lab

Department of Genetics

Washington University in St. Louis, School of Medicine

Phone: +1.608.960.1753  l  Work: ***@***.***  l  Gmail: ***@***.***

________________________________
